services:
  web:
    build:
      context: .
      dockerfile: .dockerfile
      target: deps
    working_dir: /app
    command: npm run dev
    ports:
      - "4000:4000"
      - "3000:3000"
    env_file:
      - ./src/backend/.env
      - ./src/frontend/.env
    environment:
      - PORT=4000
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=200
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/src/frontend/.next
      - /app/src/backend/dist
    develop:
      watch:
        - action: sync
          path: ./src/frontend
          target: /app/src/frontend
          ignore:
            - node_modules/
            - .next/
            - out/
        - action: sync
          path: ./src/backend
          target: /app/src/backend
          ignore:
            - node_modules/
            - dist/
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./package-lock.json
        - action: rebuild
          path: ./src/frontend/package.json
        - action: rebuild
          path: ./src/backend/package.json
